### ISSUE TITLE
PESEL validation doesn't work for older ones

### ISSUE THREAD

**Issue by piekarskipiotr** [Stempnio/pesel-validator#2]
**Description**
The program returns false when validating the PESEL of a person who is approximately 40 years old.

**Steps To Reproduce**
Validate example PESEL of person born in 1981.

![image](https://user-images.githubusercontent.com/62793427/236697667-1cc7abfa-6bfc-4a3f-b906-1d17ce1e82c3.png)

**Comment by Stempnio** [comment]
PESEL in the picture is invalid, you can check it manually
 
<img width="700" alt="Zrzut ekranu 2023-05-7 o 21 50 10" src="https://user-images.githubusercontent.com/37037163/236699624-61aab28d-cb46-4e38-b812-248f3be2a94b.png">

Source:
https://www.gov.pl/web/gov/czym-jest-numer-pesel
